### ISSUE TITLE
cleanup proposal.

### ISSUE THREAD

**Issue by ktarbet** [USACE/cc-dotnet-sdk#8]
```csharp

case StoreType.S3:
              store.Session = new FileDataStoreS3(store);
```
This case above store.Session is a Object ; and not used anywhere I can see.  
I'll create a PR that explores creating the FileDataStoreS3 in a more lazy manner and we may not need the IFileDataStore interface

**Comment by HenryGeorgist** [comment]
The session is used when finding a DataStore so that Datasources can be pulled through the plugin manager. This PR has been deleted, and the object is casted in findDataStore.
